import os
from constants.parameters import MESSAGE_LEN

DATA_FILENAME = 'audio_data'
PRETRAINED_MODELS_PATH = 'waveGAN_models'
TRAIN_DATA_PATH = 'data'

SAVE_MODELS_PATH = 'saved models'
MODEL_FOLDER_NAME = str(MESSAGE_LEN) + ' bit'
MODEL_NAME = 'autoencoder'
MODEL_EXTENSION = '.pt'

AUDIO_FOLDER = 'audio'
ORIGINAL_AUDIO_FOLDER = 'original'
STEGANOGRAPHIC_AUDIO_FOLDER = 'steganographic'
MODEL_PARAMETERS_FOLDER = 'parameters'

MODEL_PATH = os.path.join(SAVE_MODELS_PATH, MODEL_FOLDER_NAME)
ORIGINAL_AUDIO_PATH = os.path.join(MODEL_PATH, AUDIO_FOLDER, ORIGINAL_AUDIO_FOLDER)
STEGANOGRAPHIC_AUDIO_PATH = os.path.join(MODEL_PATH, AUDIO_FOLDER, STEGANOGRAPHIC_AUDIO_FOLDER)
MODEL_PARAMETERS_PATH = os.path.join(MODEL_PATH, MODEL_PARAMETERS_FOLDER)


